server:
  # 端口
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
spring:
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    # 文件上传
    servlet:
      multipart:
        # 单个文件大小
        max-file-size: 10MB
        # 设置总上传的文件大小
        max-request-size: 20MB
  # 数据源
  datasource:
    dynamic:
      enabled: true
      primary: master
      strict: false
      grace-destroy: false
      datasource:
        master:
          url: jdbc:mysql://192.168.7.3:3306/cc
          username: cc
          password: wangzhen123
          driver-class-name: com.mysql.cj.jdbc.Driver
sa-token:
  # token名称
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期，单位s 默认1天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false