spring:
  datasource:
    dynamic:
      enabled: true
      primary: master
      strict: false
      grace-destroy: false
      datasource:
        master:
          url: jdbc:mysql://192.168.7.3:3306/cc
          username: cc
          password: wangzhen123
          driver-class-name: com.mysql.cj.jdbc.Driver